# Generated by Django 5.2.3 on 2025-07-03 18:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='choices',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='form',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='response',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
