# Generated by Django 5.2.3 on 2025-07-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_answers_uid_choices_uid_form_uid_question_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
