# Generated by Django 5.2.3 on 2025-07-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_responses_options_responses_sheet_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='sheet_id',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='sheet_url',
        ),
        migrations.AddField(
            model_name='form',
            name='sheet_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='sheet_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
