# Generated by Django 5.2.3 on 2025-07-09 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_responses_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
